services:
  - type: web
    name: lets-flow-connect-backend
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
